AdtMailer.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdtMailer.Domain.Models;
using AdtMailer.Infrastructure.Interfaces.IServices;
using AdtMailer.Infrastructure.Models.CompanyViewModels;
using AdtMailer.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdtMailer.Web.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly ICompanyService companyService;
        private readonly UserManager<ApplicationUser> userManager;

        public CategoryController(ICategoryService categoryService, UserManager<ApplicationUser> userManager, ICompanyService companyService)
        {
            this.categoryService = categoryService;
            this.userManager = userManager;
            this.companyService = companyService;
        }
        // GET: Category
        public IActionResult Index()
        {
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.Companies = this.companyService.UserCompanies(userId, null).ToList();
            var categories = this.categoryService.GetCategories(userId);
            return View(categories);
        }

        // GET: Category/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Category/Edit/5
        public ActionResult Edit(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Companies = this.companyService.CategoryCompanies(id).ToList();
            var category = this.categoryService.Get(id);
            if (category == null)
            {
                RedirectToAction("Index", "Error", new { message = "Категория удалена" });
            }
            return View(category);
        }

        // POST: Category/Edit/5
        [HttpPost]   
        public ActionResult Edit(CategoryViewModel categoryViewModel)
        {
            try
            {
                categoryViewModel.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
              
                this.categoryService.Update(categoryViewModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(categoryViewModel);
            }
        }

        // GET: Category/Delete/5
        public IActionResult Delete(string id)
        {
            if (this.categoryService.Delete(id))
                return RedirectToAction("Index");
            return RedirectToAction("Error", new { message = "Невозможно удалить категорию, т.к она содержит компании" });
        }

        public IActionResult Error(string message)
        {
            var error = new ErrorViewModel() { Message = message };
            return View(error);
        }

    }
}

AdtMailer.Web/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdtMailer.Domain.Models;
using AdtMailer.Infrastructure.Interfaces.IServices;
using AdtMailer.Infrastructure.Models.CompanyViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdtMailer.Web.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly ICompanyService companyService;
        private readonly IContactService contactService;
        private readonly UserManager<ApplicationUser> userManager;
       

       public CompanyController(ICategoryService categoryService, UserManager<ApplicationUser> userManager, ICompanyService companyService,
           IContactService contactService)
        {
            this.categoryService = categoryService;
            this.userManager = userManager;
            this.companyService = companyService;
            this.contactService = contactService;
        }          
        public IActionResult Companies(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Index", "Category");
            }
            ViewBag.CategoryId = id;
            ViewBag.Category = this.categoryService.Get(id);
            var companies = this.companyService.CategoryCompanies(id);
            return View(companies);
        }
        [HttpGet]
        public IActionResult AddCompany(string id)
        {
            //ViewBag.CategoryId = id;
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.CategoryDictionary = this.categoryService.CategoryDictionary(userId);
            return View(new CompanyViewModel() { CategoryId = id });
        }
        [HttpPost]
        public IActionResult AddCompany(CompanyViewModel companyViewModel)
        {
            companyViewModel.Id = null;
            companyViewModel.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            this.companyService.Update(companyViewModel);
            return RedirectToAction("Companies", new { id = companyViewModel.CategoryId });
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Index","Category");
            }            
                      
            var company = this.companyService.Find(id);
            if (company == null)
            {
                RedirectToAction("Index", "Error", new { message = "Компания удалена" });
            }
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.Contacts = this.contactService.CompanyContacts(id);
            ViewBag.Category = this.categoryService.Get(company.CategoryId);
            ViewBag.CategoryDictionary = this.categoryService.CategoryDictionary(userId);
            return View(company);
        }
        [HttpPost]
        public IActionResult Edit(CompanyViewModel companyViewModel)
        { 
            this.companyService.Update(companyViewModel);
            return RedirectToAction("Companies", new { id = companyViewModel.CategoryId });
        }
        public IActionResult Delete(string id)
        {
            ViewBag.CategoryId = id;
            var company = this.companyService.Find(id);
            if (company == null)
            {
                RedirectToAction("Index", "Error", new { message = "Компания удалена" });
            }          
            if (this.companyService.Delete(id))
            {
                if (!String.IsNullOrWhiteSpace(company.CategoryId))
                {
                    return RedirectToAction("Companies", new { id = company.CategoryId});
                }
                return RedirectToAction("Companies");
            }
            return RedirectToAction("Index", "Error", new { message = "Компания не может быть удалена, т.к содержит контакты" });
        }
        public IActionResult Error(string message)
        {
            return View(message);
        }

    }
}

AdtMailer.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdtMailer.Domain.Models;
using AdtMailer.Infrastructure.Interfaces.IServices;
using AdtMailer.Infrastructure.Models.CompanyViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdtMailer.Web.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        private readonly IContactService contactService;
        private readonly ICompanyService companyService;
        private readonly ICategoryService categoryService;
        private readonly UserManager<ApplicationUser> userManager;
        public ContactController(IContactService contactService, UserManager<ApplicationUser> userManager,
            ICompanyService companyService, ICategoryService categoryService)
        {
            this.contactService = contactService;
            this.userManager = userManager;
            this.companyService = companyService;
            this.categoryService = categoryService;
        }        
        public IActionResult Index(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("All");
            }
            ViewBag.CompanyId = id;
            var company = this.companyService.Find(id);
            ViewBag.Company = company;
            ViewBag.Category = this.categoryService.Get(company.CategoryId);
            var contacts = this.contactService.CompanyContacts(id);
            return View(contacts);
        }
        public IActionResult All()
        {
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.CompanyDictionary = this.companyService.CompanyDictionary(userId, null);
            var contacts = this.contactService.UserContacts(userId, null).ToList();
            return View(contacts);
        }
        [HttpGet]
        public IActionResult AddContact(string id)
        {
            ViewBag.CompanyId = id;
            var userId = this.userManager.GetUserId(HttpContext.User);
            var companies = this.companyService.UserCompanies(userId, null).ToList();
            ViewBag.CompanyDictionary = companies.OrderBy(x => x.Name).ToDictionary(key => key.Id, value => value.Name);
            return View(new ContactViewModel() { CompanyId = id});
        }

        [HttpPost]
        public IActionResult AddContact(ContactViewModel contact)
        {
            contact.Id = null;
            contact.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            if (this.contactService.Update(contact))
            if (String.IsNullOrWhiteSpace(contact.CompanyId))
            {
                return RedirectToAction("All");
            }
            return RedirectToAction("Index", new { id = contact.CompanyId });

        }
        [HttpGet]
        public IActionResult Update(string id)
        {        
            var contact = this.contactService.Find(id);
            if (contact == null)
            {
                RedirectToAction("Error", "Index", new { message = "Контакт удален" });
            }
            var userId = this.userManager.GetUserId(HttpContext.User);
            var companies = this.companyService.UserCompanies(userId, null).ToList();
            ViewBag.CompanyDictionary = companies.OrderBy(x => x.Name).ToDictionary(key => key.Id, value => value.Name);
            if (!String.IsNullOrWhiteSpace(contact.CompanyId))
            {
                var company = this.companyService.Find(contact.CompanyId);
                ViewBag.Company = company;
                ViewBag.Category = this.categoryService.Get(company.CategoryId);
            }
            return View(contact);
        }

        [HttpPost]
        public IActionResult Update(ContactViewModel contact)
        {
            contact.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            if (this.contactService.Update(contact))
            {
                if (String.IsNullOrWhiteSpace(contact.CompanyId))
                {
                    return RedirectToAction("All");
                }
                return RedirectToAction("Index", new { id = contact.CompanyId });
            }
            throw new ArgumentNullException();
        }
        [HttpGet]
        public IActionResult Delete(string contactId, string companyId)
        {            
            var contact = this.contactService.Delete(contactId);
            if (String.IsNullOrWhiteSpace(companyId))
            {
                return RedirectToAction("All");
            }
            return RedirectToAction("Index", new { id = companyId });
        }
    }
}

AdtMailer.Web/Views/Category/Create.cshtml
@model AdtMailer.Infrastructure.Models.CompanyViewModels.CategoryViewModel

@{
	ViewData["Title"] = "AddCategoty";
	Layout = "_LayoutFeed";
}

<h4>Новая категория</h4>
<div>
	<a asp-action="Index">К списку категорий</a>
</div>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label">Название</label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label">Примечание</label>
				<textarea asp-for="Description" rows="3" class="form-control"></textarea>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Сохранить" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>

AdtMailer.Web/Views/Category/Edit.cshtml
@model AdtMailer.Infrastructure.Models.CompanyViewModels.CategoryViewModel
@using AdtMailer.Infrastructure.Models.CompanyViewModels
@using AdtMailer.DataTransferObject.Enums
@{
	ViewData["Title"] = "UpdateCategory";
	Layout = "~/Views/Shared/_LayoutFeed.cshtml";
	var companies = ViewBag.Companies;
}

<h4>Категория: <a href="/company/companies/@Model.Id"> @Model.Name </a></h4>
<div>
	<a asp-action="Index">К списку категорий</a>
</div>
<div class="row">
	<a href="#" type="button" class="btn btn-success" style="margin-top: 5px">Создать рассылку</a>
</div>
<hr />
<div class="row">
	<div class="col-md-6">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group" style="display: none">
				<label asp-for="Id" class="control-label"></label>
				<input asp-for="Id" class="form-control" />
				<span asp-validation-for="Id" class="text-danger"></span>
			</div>
			<div class="form-group" style="display: none">
				<label asp-for="ApplicationUserId" class="control-label"></label>
				<input asp-for="ApplicationUserId" class="form-control" />
				<span asp-validation-for="ApplicationUserId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Name" class="control-label">Название</label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label">Примечание</label>
				<textarea asp-for="Description" rows="3" class="form-control"></textarea>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<div class="row">
					<input type="submit" value="Сохранить" class="btn btn-default" />
					<a style="margin-left: 10px" href="/category/delete/@Model.Id" type="button" class="btn btn-danger">Удалить</a>
				</div>
			</div>
		</form>
	</div>
	<div class="col-md-6">

		@try
		{
			@if (ViewBag.Companies != null && ((List<CompanyViewModel>)ViewBag.Companies).Any())
			{
				<table class="table table-striped table-hover">
					<tbody>
						<tr>
							<th>
								Компании
							</th>
							<th>
								Описание
							</th>
							<th>
								<a href="/company/AddCompany/@Model.Id" type="button" class="btn btn-success">Добавить</a>
							</th>

						</tr>
						@foreach (var item in (IEnumerable<AdtMailer.Infrastructure.Models.CompanyViewModels.CompanyViewModel>)companies)
						{
							<tr>
								<td><a href="/company/edit/@item.Id">@Html.DisplayFor(modelItem => item.Name)</a></td>
								<td>@(item.Description?.Length > 20 ? item.Description.Substring(0, 20) + "..." : item.Description)</td>
								<td>@Html.ActionLink("Сотрудники", "Index", "Contact", new { id = item.Id }) </td>
							</tr>
						}

					</tbody>
				</table>
			}
			else
			{
				<p>Пока не добавлено ни одной компании</p>
			}
		}
		catch (Exception ex)
		{
			<p>Пока не добавлено ни одной компании</p>
		}

	</div>
</div>

AdtMailer.Web/Views/Category/Index.cshtml
@model IEnumerable<AdtMailer.Infrastructure.Models.CompanyViewModels.CategoryViewModel>
@using AdtMailer.Infrastructure.Models.CompanyViewModels
@{
	ViewData["Title"] = "Index";
	Layout = "_LayoutFeed";
}

<div class="row">
	<div class="col-md-6">
		<div class="row">
			<h2 style="margin-right: 10px">Категории</h2>
			<a href="/category/create" type="button" class="btn btn-success" style="margin-top: 5px">Добавить</a>
		</div>
	</div>
	<div class="col-md-6">
		<div class="row">
			<h2 style="margin-right: 10px">Компании</h2>
			<a href="/company/addcompany" type="button" class="btn btn-success" style="margin-top: 5px">Добавить</a>
		</div>
	 </div>
</div>
<div class="row" style="margin-top: 5px">
	<div class="col-md-6">
		<table class="table table-striped table-hover">
			<thead>
				<tr>		
					<th>
						Название
					</th>
					<th>
						Описание
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.ActionLink(item.Name, "Companies", "Company", new { id = item.Id })
						</td>
						<td>
							@(item.Description?.Length > 20 ? item.Description.Substring(0, 20) + "..." : item.Description)
						</td>
						<td>
							<a href="/category/edit/@item.Id" >Открыть</a> |
							@Html.ActionLink("Удалить", "Delete", new { id = item.Id })
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
	<div class="col-md-6">
		@try
		{
			@if (ViewBag.Companies != null && ((List<CompanyViewModel>)ViewBag.Companies).Any())
			{
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>
						Название
					</th>
					<th>
						Сайт
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in (IEnumerable<AdtMailer.Infrastructure.Models.CompanyViewModels.CompanyViewModel>)ViewBag.Companies)
				{
				<tr>
					<td><a href="/contact/index/@item.Id">@Html.DisplayFor(modelItem => item.Name)</a></td>
					<td><a href=@item.Site> @item.Site</a></td>	
					<td>
						<a href="/company/edit/@item.Id">Открыть</a> |
						@Html.ActionLink("Удалить", "Delete","Company", new { id = item.Id })
					</td>
				</tr>
				}

			</tbody>
		</table>
			}
			else
			{
				<p>Пока не добавлено ни одной компании</p>


			}
		}
		catch (Exception ex)
		{
			<p>Пока не добавлено ни одной компании</p>
		}
	</div>
</div>