AdtMailer.Web/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdtMailer.Domain.Models;
using AdtMailer.Infrastructure.Interfaces.IServices;
using AdtMailer.Infrastructure.Models.CompanyViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdtMailer.Web.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly ICompanyService companyService;
        private readonly IContactService contactService;
        private readonly UserManager<ApplicationUser> userManager;
       

       public CompanyController(ICategoryService categoryService, UserManager<ApplicationUser> userManager, ICompanyService companyService,
           IContactService contactService)
        {
            this.categoryService = categoryService;
            this.userManager = userManager;
            this.companyService = companyService;
            this.contactService = contactService;
        }          
        public IActionResult Companies(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Index", "Category");
            }
            ViewBag.CategoryId = id;
            ViewBag.Category = this.categoryService.Get(id);
            var companies = this.companyService.CategoryCompanies(id);
            return View(companies);
        }
        [HttpGet]
        public IActionResult AddCompany(string id)
        {
            //ViewBag.CategoryId = id;
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.CategoryDictionary = this.categoryService.CategoryDictionary(userId);
            return View(new CompanyViewModel() { CategoryId = id });
        }
        [HttpPost]
        public IActionResult AddCompany(CompanyViewModel companyViewModel)
        {
            companyViewModel.Id = null;
            companyViewModel.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            this.companyService.Update(companyViewModel);
            return RedirectToAction("Companies", new { id = companyViewModel.CategoryId });
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("Index","Category");
            }            
                      
            var company = this.companyService.Find(id);
            if (company == null)
            {
                RedirectToAction("Index", "Error", new { message = "Компания удалена" });
            }
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.Contacts = this.contactService.CompanyContacts(id);
            ViewBag.Category = this.categoryService.Get(company.CategoryId);
            ViewBag.CategoryDictionary = this.categoryService.CategoryDictionary(userId);
            return View(company);
        }
        [HttpPost]
        public IActionResult Edit(CompanyViewModel companyViewModel)
        { 
            this.companyService.Update(companyViewModel);
            return RedirectToAction("Companies", new { id = companyViewModel.CategoryId });
        }
        public IActionResult Delete(string id)
        {
            ViewBag.CategoryId = id;
            var company = this.companyService.Find(id);
            if (company == null)
            {
                RedirectToAction("Index", "Error", new { message = "Компания удалена" });
            }          
            if (this.companyService.Delete(id))
            {
                if (!String.IsNullOrWhiteSpace(company.CategoryId))
                {
                    return RedirectToAction("Companies", new { id = company.CategoryId});
                }
                return RedirectToAction("Companies");
            }
            return RedirectToAction("Index", "Error", new { message = "Компания не может быть удалена, т.к содержит контакты" });
        }
        public IActionResult Error(string message)
        {
            return View(message);
        }

    }
}

AdtMailer.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdtMailer.Domain.Models;
using AdtMailer.Infrastructure.Interfaces.IServices;
using AdtMailer.Infrastructure.Models.CompanyViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdtMailer.Web.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        private readonly IContactService contactService;
        private readonly ICompanyService companyService;
        private readonly ICategoryService categoryService;
        private readonly UserManager<ApplicationUser> userManager;
        public ContactController(IContactService contactService, UserManager<ApplicationUser> userManager,
            ICompanyService companyService, ICategoryService categoryService)
        {
            this.contactService = contactService;
            this.userManager = userManager;
            this.companyService = companyService;
            this.categoryService = categoryService;
        }        
        public IActionResult Index(string id)
        {
            if (String.IsNullOrWhiteSpace(id))
            {
                return RedirectToAction("All");
            }
            ViewBag.CompanyId = id;
            var company = this.companyService.Find(id);
            ViewBag.Company = company;
            ViewBag.Category = this.categoryService.Get(company.CategoryId);
            var contacts = this.contactService.CompanyContacts(id);
            return View(contacts);
        }
        public IActionResult All()
        {
            var userId = this.userManager.GetUserId(HttpContext.User);
            ViewBag.CompanyDictionary = this.companyService.CompanyDictionary(userId, null);
            var contacts = this.contactService.UserContacts(userId, null).ToList();
            return View(contacts);
        }
        [HttpGet]
        public IActionResult AddContact(string id)
        {
            ViewBag.CompanyId = id;
            var userId = this.userManager.GetUserId(HttpContext.User);
            var companies = this.companyService.UserCompanies(userId, null).ToList();
            ViewBag.CompanyDictionary = companies.OrderBy(x => x.Name).ToDictionary(key => key.Id, value => value.Name);
            return View(new ContactViewModel() { CompanyId = id});
        }

        [HttpPost]
        public IActionResult AddContact(ContactViewModel contact)
        {
            contact.Id = null;
            contact.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            if (this.contactService.Update(contact))
            if (String.IsNullOrWhiteSpace(contact.CompanyId))
            {
                return RedirectToAction("All");
            }
            return RedirectToAction("Index", new { id = contact.CompanyId });

        }
        [HttpGet]
        public IActionResult Update(string id)
        {        
            var contact = this.contactService.Find(id);
            if (contact == null)
            {
                RedirectToAction("Error", "Index", new { message = "Контакт удален" });
            }
            var userId = this.userManager.GetUserId(HttpContext.User);
            var companies = this.companyService.UserCompanies(userId, null).ToList();
            ViewBag.CompanyDictionary = companies.OrderBy(x => x.Name).ToDictionary(key => key.Id, value => value.Name);
            if (!String.IsNullOrWhiteSpace(contact.CompanyId))
            {
                var company = this.companyService.Find(contact.CompanyId);
                ViewBag.Company = company;
                ViewBag.Category = this.categoryService.Get(company.CategoryId);
            }
            return View(contact);
        }

        [HttpPost]
        public IActionResult Update(ContactViewModel contact)
        {
            contact.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            if (this.contactService.Update(contact))
            {
                if (String.IsNullOrWhiteSpace(contact.CompanyId))
                {
                    return RedirectToAction("All");
                }
                return RedirectToAction("Index", new { id = contact.CompanyId });
            }
            throw new ArgumentNullException();
        }
        [HttpGet]
        public IActionResult Delete(string contactId, string companyId)
        {            
            var contact = this.contactService.Delete(contactId);
            if (String.IsNullOrWhiteSpace(companyId))
            {
                return RedirectToAction("All");
            }
            return RedirectToAction("Index", new { id = companyId });
        }
    }
}

AdtMailer.Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdtMailer.Domain.Models;
using AdtMailer.Infrastructure.Interfaces.IServices;
using AdtMailer.Infrastructure.Models.MailViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AdtMailer.Web.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        private readonly IMailService mailService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ISettingsService settingsService;
        private static readonly byte[] trackingGif =
        {
            0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x1, 0x0, 0x1, 0x0, 0x80, 0x0, 0x0, 0xff,
            0xff, 0xff, 0x0, 0x0, 0x0, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1, 0x0, 0x0,
            0x2, 0x2, 0x44, 0x1, 0x0, 0x3b
        };
        public MessageController(IMailService mailService, UserManager<ApplicationUser> userManager, ISettingsService settingsService)
        {
            this.mailService = mailService;
            this.userManager = userManager;
            this.settingsService = settingsService;
        }
        public IActionResult Index()
        {
            var userId = this.userManager.GetUserId(HttpContext.User);
            var emails = this.mailService.GetMails(userId);
            return View(emails);
        }
        [HttpGet]
        public IActionResult Create(MailViewModel mail)
        {
            var userId = this.userManager.GetUserId(HttpContext.User);
            var settings = this.settingsService.Find(userId);
            mail.From = settings.FirstName + " " + settings.SecondName;
            return View(mail);
        }


        [HttpPost]
        public async Task<IActionResult> Send(MailViewModel mail)
        {
            mail.ApplicationUserId = this.userManager.GetUserId(HttpContext.User);
            await this.mailService.SendAsync(mail, Request.Host.Value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public FileResult AddClick(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return null;
            }           
            this.mailService.AddClick(id);
           // asyncRunner.Run(() => mailStatisticsService.AddClick(key), AsyncRunnerOptions.BackgroundThread);

            return File(trackingGif, "image/gif");
        }
    }
}

AdtMailer.Web/Views/Contact/AddContact.cshtml
@model AdtMailer.Infrastructure.Models.CompanyViewModels.ContactViewModel
@using AdtMailer.DataTransferObject.Enums
@using AdtMailer.Infrastructure.Models.CompanyViewModels
@{
	ViewData["Title"] = "AddContact";
	Layout = "~/Views/Shared/_LayoutFeed.cshtml";
	var companyDictionary = (Dictionary<string, string>)ViewBag.CompanyDictionary;
	var companies = new List<CompanyViewModel>() { new CompanyViewModel() { Id = "", Name = "Без компании" } };
	companies.AddRange(companyDictionary.Select(x => new CompanyViewModel() { Id = x.Key, Name = x.Value }));
	var companySelectList = new SelectList(companies, "Id", "Name");
}

<h4>Новый контакт</h4>
<div>
	<a asp-action="Index/@ViewBag.CompanyId">К списку контактов</a>
</div>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="AddContact">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label">Имя</label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CompanyId" class="control-label">Компания</label>
				<select asp-for="CompanyId" asp-items="@companySelectList" class="form-control"></select>
			</div>
			<div class="form-group">
				<label asp-for="Status" class="control-label">Статус</label>
				<select asp-for="Status" asp-items="Html.GetEnumSelectList<ClientStatus>()" class="form-control"></select>
			</div>
			<div class="form-group">
				<label asp-for="Position" class="control-label">Должность</label>
				<input asp-for="Position" class="form-control" />
				<span asp-validation-for="Position" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Emails" class="control-label">Почта</label>
				<input asp-for="Emails" class="form-control" placeholder="Введите почтоные ящики через запятую" />
				<span asp-validation-for="Emails" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Phone" class="control-label">Телефон</label>
				<input asp-for="Phone" class="form-control" />
				<span asp-validation-for="Phone" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Skype" class="control-label">Skype</label>
				<input asp-for="Skype" class="form-control" />
				<span asp-validation-for="Skype" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Social" class="control-label">Социальные сети</label>
				<input asp-for="Social" class="form-control" />
				<span asp-validation-for="Social" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label">Примечание</label>
				<textarea asp-for="Description" rows="3" class="form-control"></textarea>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Сохранить" class="btn btn-default" />
			</div>
		</form>
    </div>
</div>

AdtMailer.Web/Views/Contact/All.cshtml
@model IEnumerable<AdtMailer.Infrastructure.Models.CompanyViewModels.ContactViewModel>

@{
	ViewData["Title"] = "All";
	Layout = "~/Views/Shared/_LayoutFeed.cshtml";
	var companyDictionary = (Dictionary<string, string>)ViewBag.CompanyDictionary;
}

<div class="row">	
		<h2 style="margin-right: 10px">Контакты</h2>
		<a href="/contact/AddContact/@ViewBag.CompanyId" type="button" class="btn btn-success" style="margin-top: 5px">Добавить</a>
</div>
<table class="table" style="margin-top: 5px">
    <thead>
		<tr>
			<td>
				Имя
			</td>
			<td>
				Почта
			</td>
			<td>
				Телефон
			</td>
			<td>
				Должность
			</td>
			<td>
				Добавлен
			</td>
			<td>
				Статус
			</td>
			<td>
				Компания
			</td>
			<th></th>
		</tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
	string str = "...";
	var color = "white";

	if ((int)item.Status == 0)
	{
		color = "background-color: ghostwhite;";
	}
	if ((int)item.Status == 1)
	{
		color = "background-color: gainsboro;";
	}
	if ((int)item.Status == 2)
	{
		color = "background-color: darkseagreen;";
	}
	if ((int)item.Status == 3)
	{
		color = "background-color: tomato;";
	}
	if ((int)item.Status == 4)
	{
		color = "background-color: gold;";
	}

	if (!String.IsNullOrWhiteSpace(item.Emails) && item.Emails.Length > 20) { str = item.Emails.Substring(0, 20); }
	if (!String.IsNullOrWhiteSpace(item.Emails) && item.Emails.Length <= 20) { str = item.Emails; }
	if (String.IsNullOrWhiteSpace(item.Emails)) { str = "..."; }
		<tr style="@color">
			<td>
				<a href="/contact/update/@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
			</td>
			<td>				
				@Html.ActionLink(str, "Create", "Message", new { ApplicationUserId = item.Id, CompanyId = item.CompanyId, Emails = item.Emails })
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Phone)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Position)
			</td>
			<td>
				@item.DateCreated.ToShortDateString()
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Status)
			</td>
			<td>
				<a href="/company/edit/@item.CompanyId"> @(item.CompanyId != null && (companyDictionary.ContainsKey(item.CompanyId)) ? companyDictionary[item.CompanyId] : "...")</a>
			</td>
			<td>
				@Html.ActionLink("Удалить", "Delete", new { contactId = item.Id })
			</td>
		</tr>
}
    </tbody>
</table>

AdtMailer.Web/Views/Contact/Index.cshtml
@model IEnumerable<AdtMailer.Infrastructure.Models.CompanyViewModels.ContactViewModel>
@using AdtMailer.DataTransferObject.Enums
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_LayoutFeed.cshtml";
	var company = ViewBag.Company;
	var category = ViewBag.Category;
}

<h4>Категория: <a href="/company/companies/@category?.Id">@category?.Name</a> >> Компания: @Html.ActionLink((string)company.Name, "Edit", "Company", new { id = company.Id }) >> Контакты</h4>

<div class="row">
	<div class="col-md-2" style="margin-top: 5px">
		<p>
			<a href="/contact/AddContact/@ViewBag.CompanyId" type="button" class="btn btn-success">Добавить контакт</a>
		</p>
	</div>
	<div class="col-md-2" style="margin-top: 5px">
		<p>
			<a href="#" type="button" class="btn btn-success">Создать рассылку</a>
		</p>
	</div>
</div>
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				Имя
			</th>
			<th>
				Должность
			</th>
			<th>
			    Почта
			</th>
			<th>
				Добавлен
			</th>
			<th>
				Статус
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			string str = "...";

			if (!String.IsNullOrWhiteSpace(item.Emails) && item.Emails.Length > 20) { str = item.Emails.Substring(0, 20); }
			if (!String.IsNullOrWhiteSpace(item.Emails) && item.Emails.Length <= 20) { str = item.Emails; }
			if (String.IsNullOrWhiteSpace(item.Emails)) { str = "..."; }
			<tr>
				<td>				
					<a href="/contact/update/@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Position)
				</td>
				<td>
					@Html.ActionLink(str, "Create", "Message", new { ApplicationUserId = item.Id, CompanyId = item.CompanyId, Emails = item.Emails })
				</td>
				<td>
					@item.DateCreated.ToShortDateString()
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Status)
				</td>
				<td>				
					@Html.ActionLink("Удалить", "Delete", new { contactId = item.Id, companyId = item.CompanyId })
				</td>
			</tr>
		}
	</tbody>
</table>

AdtMailer.Web/Views/Contact/Update.cshtml
@model AdtMailer.Infrastructure.Models.CompanyViewModels.ContactViewModel
@using AdtMailer.DataTransferObject.Enums
@using AdtMailer.Infrastructure.Models.CompanyViewModels

@{
	ViewData["Title"] = "Update";
	Layout = "~/Views/Shared/_LayoutFeed.cshtml";
	var company = ViewBag.Company;
	var category = ViewBag.Category;

	var companyDictionary = (Dictionary<string, string>)ViewBag.CompanyDictionary;
	var companies = new List<CompanyViewModel>() { new CompanyViewModel() { Id = "", Name = "Без компании" } };
	companies.AddRange(companyDictionary.Select(x => new CompanyViewModel() { Id = x.Key, Name = x.Value }));
	var companySelectList = new SelectList(companies, "Id", "Name");
}

@{if (company != null && category != null)
	{
		<h4>Категория: <a href="/category/edit/@category.Id">@category.Name</a> >> Компания: <a href="/company/edit/@company.Id">@company.Name</a> >> @Model.Name</h4>
	}
	else
	{
		<h3>@Model.Name</h3>
	}
}
<div>
	<a asp-action="Index/@Model.CompanyId">К списку сотрудников</a>
</div>
@Html.ActionLink("Сообщение", "Create", "Message",  new { ApplicationUserId = Model.Id, CompanyId = Model.CompanyId }, new { @type = "button", @class= "btn btn-success", @style = "margin-top: 5px" })
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Update">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group" style="display: none">
				<label asp-for="Id" class="control-label"></label>
				<input asp-for="Id" class="form-control" />
				<span asp-validation-for="Id" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Name" class="control-label">Имя</label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="CompanyId" class="control-label">Компания</label>
				<select asp-for="CompanyId" asp-items="@companySelectList" class="form-control"></select>
			</div>
			<div class="form-group">
				<label asp-for="Status" class="control-label">Статус</label>
				<select asp-for="Status" asp-items="Html.GetEnumSelectList<ClientStatus>()" class="form-control"></select>
			</div>
			<div class="form-group">
				<label asp-for="Position" class="control-label">Должность</label>
				<input asp-for="Position" class="form-control" />
				<span asp-validation-for="Position" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Emails" class="control-label">Почта</label>
				<input asp-for="Emails" class="form-control" />
				<span asp-validation-for="Emails" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Phone" class="control-label">Телефон</label>
				<input asp-for="Phone" class="form-control" />
				<span asp-validation-for="Phone" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Skype" class="control-label">Skype</label>
				<input asp-for="Skype" class="form-control" />
				<span asp-validation-for="Skype" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Social" class="control-label">Социальные сети</label>
				<input asp-for="Social" class="form-control" />
				<span asp-validation-for="Social" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label">Примечание</label>
				<textarea asp-for="Description" rows="3" class="form-control"></textarea>
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Сохранить" class="btn btn-default" />
				<a style="margin-left: 10px" href="/contact/delete?contactId=@Model.Id" type="button" class="btn btn-danger">Удалить</a>
			</div>
		</form>
	</div>
</div>